# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: VIEW§ - Indented Statute Viewer
email: hellomcknight@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Laws are easier to read and understand when they are indented, searchable,
  cite to their history, and cite to caselaw. VIEW§ is a tool that tries to
  do just that for Florida's Workers' Compensation Law.
baseurl: "" # the subpath of your site, e.g. /blog
url: "/views/" # the base hostname & protocol for your site
github_username:  dmck
exclude:
  - node_modules
# Build settings
markdown: kramdown
